server:
  port: 8883

spring:
  application:
    name: helloworld
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  thymeleaf:
    cache: false


mq:
  config:
    exchange: log.direct #设置交换器名称
    queue:
      info:
        routing:
          key: log.info.routing.key #info的路由键
      error: log.error #error队列名称


#student:
#  email: 15224719330@163.com
#  uname: zs #可与properties互补使用
##  age: 23
#  sex: true
#  birthday: 2019/02/23
#  location:
#    province: 河南1
#    city: 信阳1
#    zone: 浉河区1
#    #{province: "河\n南",city: '信\n阳',zone: 浉\n河区} #行内写法 #默认可以不写引号:""（双引号）会将转义符进行转义
#  hobbies: [足球,篮球] #行内写法
# #   - 足球
# #   - 篮球
#  skills:
#    [编程,金融] #行内写法
# #   - 编程
# #   - 金融
#  pet: {nick-name: gouzi,strain: jb}
# #   nickName: wc
# #   strain: hsq